---
version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:15rc2-bullseye
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./.data/postgres/data:/var/lib/postgres/data
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
